### ISSUE TITLE
Product Management Service - Schema Design

### ISSUE THREAD

**Issue by thisissvikas** [thisissvikas/shop-keeper#4]
## Problem Statement
Decide the database and design the schema for product resources.

## Acceptance Criteria
- [x] Database choice finalised
- [x] Schema design ready
- [x] All [guidelines](https://github.com/krvikas1011/shop-keeper/issues/3) are followed.

child of: https://github.com/krvikas1011/shop-keeper/issues/2

**Comment by shubhaangi04** [comment]
# Database Technology: 
## SQL 
- Data requirements are clear.
- Data is structured and organized.
- In case of semi-structured data (key-value pair), we can use JSON data type to store the data.

## MySQL vs PostgreSQL
- Mostly they're the same, the advanced features that PostgreSQL provides, we don't see the use case of that in our project.

**Comment by thisissvikas** [comment]
@shubhaangi04 Too abstract. It will make more sense if you write in terms of this service and then draw the advantages of the choices made.

**Comment by shubhaangi04** [comment]
In the product management service, we are clear of the fields that we will be requiring like the product ID, name, price, category, description, specification, etc. and these fields will be common across all the products. The product specification field will be different for each product's category, thus we can use the JSON data type provided by MySQL.
